spring:
  datasource:
    url: jdbc:mysql:///shiro?serverTimezone=UTC
    username: root
    password: 4071302
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8082
